import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Geist_Mono({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "AI Agent", //todo
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>{children}</body>
    </html>
  );
}
